# Generated by Django 3.2.7 on 2021-12-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
                ('size', models.TextField()),
                ('prize', models.IntegerField()),
                ('img', models.ImageField(upload_to='product')),
                ('desc', models.TextField()),
            ],
        ),
    ]
